### PR TITLE
Created install script, updated wrapper script with new doctor usage.

### PR DESCRIPTION
**Pull request by nathanagood**

### CODE REVIEW

**Review by davidstacy — CHANGES_REQUESTED** [review]
* itz version results in blank return - fix?
* itz doctor still showing one unmet requirement, not sure why. doctor autofix doesnt fix yet.  I can consult on why this is.
* itz list environments results in panic runtime error - probably should remove environments from list

**Comment by davidstacy** [comment]
image

itz doctor 11 things checked all ok but one unmet requirement at end.
image

**Comment by nathanagood** [comment]
@davidstacy, I'm catching all of these in a different PR:
> itz version results in blank return - fix?
> itz doctor still showing one unmet requirement, not sure why. doctor autofix doesnt fix yet. I can consult on why this is.
> itz list environments results in panic runtime error - probably should remove environments from list

The `itz version` is blank because you need to do a `git fetch --all --tags` to pull the tags down locally when building locally. You do _not_ need to do this when doing a brew install because that uses a hardcoded value that is set in the .rb file.

The `list environments` command has been removed in a subsequent PR (just about to push it up).

I'll check on the `doctor -f`, as that is what this PR is supposed to address.

**Comment by nathanagood** [comment]
Merging after discussing with @davidstacy

**Pull request merged**
